INSERT INTO "public"."directorate" ("name") VALUES
('AYUDANTIA POLICIAL'),
('DIRECCION ADMINISTRACION'),
('DIRECCION ASUNTOS JURIDICOS'),
('DIRECCION BENEFICIARIOS'),
('DIRECCION DE CONTROL Y PREVENCION'),
('DIRECCION DE INFORMATICA Y SISTEMAS'),
('DIRECCION DE RECURSOS HUMANOS'),
('DIRECCION GENERAL DE OPERACIONES'),
('PRESIDENCIA'),
('SECRETARIA GENERAL'),
('UNIDAD DE AUDITORIA INTERNA');