INSERT INTO "public"."government_institutions" ("name") VALUES
('Ministerio de Economía'),
('Asesoría General de Gobierno'),
('Ministerio de Infraestructura y Servicios Públicos'),
('Ministerio de Seguridad'),
('Ministerio de Producción, Ciencia e Innovación Tecnológica'),
('Ministerio de Ciencia, Tecnología e Innovación'),
('Contaduría General de la Provincia'),
('Ministerio de Desarrollo Agrario'),
('Dirección General de Cultura y Educación'),
('Fiscalía'),
('Fiscalía de Estado'),
('Honorable Tribunal de Cuentas'),
('Ministerio de Hábitat y Desarrollo Urbano'),
('Instituto Cultural de la Provincia de Buenos Aires'),
('Ministerio de Salud'),
('Ministerio de Trabajo'),
('Ministerio de Jefatura de Gabinete de Ministros'),
('JUNTA ELECTORAL'),
('Ministerio de Desarrollo de la Comunidad'),
('Ministerio de Justicia y Derechos Humanos'),
('Tesorería General de la Provincia');