INSERT INTO "public"."institutional_departments" ("name", "government_institutions_fk") VALUES
('Agencia de Recaudación de la Provincia de Buenos Aires', 1),
('Subdirección Ejecutiva de Recaudación y Catastro', 1),
('Subdirección Ejecutiva de Acciones Territoriales y Servicios', 1),
('Subdirección Ejecutiva de Asuntos Jurídicos', 1),
('Subdirección Ejecutiva de Administración y Tecnología', 1),
('GERENCIA GENERAL DE COMUNICACIÓN Y RELACIONES INSTITUCIONALES', 1),
('GERENCIA GENERAL DE AUDITORÍA Y RESPONSABILIDAD PROFESIONAL', 1),
('Unidad de Asistencia Técnica Integral', 1),
('Gerencia General de Recaudación', 1),
('Gerencia General de Cobranzas', 1),
('Gerencia General de Catastro y Geodesia', 1),
('Gerencia General de Estudios Económicos y Estadísticas Tributarias', 1),
('Gerencia General de Fiscalización Individualizada', 1),
('Gerencia General de Fiscalización Masiva', 1),
('Gerencia General de Coordinación de Atención y Servicios', 1),
('Gerencia General de Coordinación Jurídica', 1),
('Gerencia General de Técnica Tributaria y Catastral', 1),
('Gerencia General de Administración', 1),
('Gerencia General de Tecnología e Innovación', 1),
('Coordinador Técnico Institucional', 1),
('Asesoría General de Gobierno', 2),
('Asesoría General de Gobierno Adjunto', 2),
('Asesoría Ejecutiva', 2),
('DIRECCIÓN GENERAL DE ADMINISTRACIÓN', 2),
('DIRECCIÓN GENERAL DE PLANIFICACIÓN Y DE INFORMACIÓN JURÍDICA', 2),
('DIRECCIÓN DE RELACIONES INSTITUCIONALES', 2),
('ESCUELA DE ABOGACÍA DE LA ADMINISTRACIÓN PÚBLICA PROVINCIAL', 2),
('SECRETARÍA LETRADA 1', 2),
('DIRECCIÓN DE CONTABILIDAD Y SERVICIOS AUXILIARES', 2),
('DIRECCIÓN DELEGADA DE LA DIRECCIÓN PROVINCIAL DE PERSONAL', 2),
('DIRECCIÓN DE GESTIÓN TÉCNICA Y ADMINISTRATIVA', 2),
('DIRECCIÓN DE SERVICIOS DE COMUNICACIÓN E INFORMÁTICA', 2),
('DIRECCIÓN DE PLANIFICACIÓN Y CONTROL DE GESTIÓN', 2),
('DIRECCIÓN DE REUNIÓN Y SISTEMATIZACIÓN DE INFORMACIÓN JURÍDICA', 2),
('RELATORES JEFES RELATORES DELEGADOS', 2),
('Subdirección de Contabilidad y Servicios Auxiliares', 2),
('Subdirección de Sistematización de Información Jurídica', 2),
('Subsecretaría de Recursos Hídricos', 3),
('Autoridad del Agua (Presidencia)', 3),
('AUTORIDAD DEL AGUA (Vicepresidencia)', 3),
('Autoridad del Agua (vocal I)', 3),
('Autoridad del Agua (vocal II)', 3),
('Dirección Provincial de Planes Hídricos, Monitoreo y Alerta', 3),
('Dirección Provincial de Gestión Hídrica', 3),
('Dirección Provincial de Calidad y Control del Servicio Sanitario', 3),
('Dirección General de Administración', 3),
('Ministerio de Seguridad', 4),
('Caja de Retiros, Jubilaciones y Pensiones (Directorio)', 4),
('Vicepresidencia', 4),
('Subsecretaría de Ciencia, Tecnología e Innovación', 5),
('Comisión de Investigaciones Científicas (CIC)', 5),
('Directorio', 5),
('Directorio', 6),
('Dirección Provincial de Comunicación y Divulgación Científica', 5),
('Dirección Provincial de Vinculación y Transferencia', 5),
('Dirección Provincial de Gestión, Seguimiento y Desarrollo de la Actividad Científica', 5),
('Dirección Provincial de Administración Científica y Técnica', 5),
('Comité de Cuenca del Río Luján (COMILU)', 3),
('Dirección General Ejecutiva (COMILU)', 3),
('DIRECTORIO COMILU', 3),
('COMITÉ DE CUENCA DEL RÍO RECONQUISTA (COMIREC)', 3),
('Dirección General Ejecutiva (COMIREC)', 3),
('DIRECTORIO', 3),
('Contaduría General de la Provincia', 7),
('Sub Contaduría General', 7),
('Secretaría de Contabilidad y Control de Gestión', 7),
('Secretaría Legal y Técnica (CG)', 7),
('Dirección General de Administración', 7),
('Dirección General de Centro de Sistemas e Informática', 7),
('Dirección General de Control Contable', 7),
('Dirección General de Auditoría', 7),
('Dirección General de Contabilidad e Información', 7),
('Dirección General de Autorizaciones de Pago', 7),
('Dirección General de Dictámenes', 7),
('Dirección General de Procedimientos Especiales', 7),
('Ministerio de Desarrollo Agrario', 8),
('Corporación de Fomento del Valle del Río Colorado (CORFO)', 8),
('GERENCIA TÉCNICA', 8),
('Subsecretaría de Obras Públicas', 3),
('Dirección de Vialidad', 3),
('Subadministración General', 3),
('DIRECCIÓN GENERAL INMOBILIARIA Y SOCIAL', 3),
('Gerencia Técnica', 3),
('Gerencia de Administración', 3),
('Gerencia Ejecutiva', 3),
('Dirección General de Cultura y Educación', 9),
('Dirección Provincial de Legal y Técnica', 9),
('Dirección Provincial de Comunicación', 9),
('Dirección Provincial de Consejos Escolares y Coordinación Institucional', 9),
('Auditoría General', 9),
('Consejo General de Cultura y Educación', 9),
('Consejo Provincial de Educación y Trabajo (COPRET)', 9),
('Subsecretaría de Planeamiento', 9),
('Subsecretaría de Infraestructura Escolar', 9),
('Subsecretaría de Educación', 9),
('Subsecretaría de Administración y Recursos Humanos', 9),
('Dirección de Coordinación Administrativa', 9),
('Dirección de Coordinación de Actuaciones Judiciales', 9),
('Dirección de Sumarios', 9),
('Dirección de Legal y Técnica Administrativa', 9),
('Dirección Legal y Técnica Educativa', 9),
('Dirección de Comunicación Institucional', 9),
('Dirección de Cooperación Escolar', 9),
('Dirección de Coordinación de Políticas Alimentarias, Accesibilidad y Salud', 9),
('Dirección de Administración de Consejos Escolares', 9),
('Dirección de Auditoria', 9),
('Secretaría Administrativa', 9),
('Dirección de Promoción de Educación y Trabajo', 9),
('Dirección de Información y Estadística', 9),
('Dirección Provincial de Evaluación e Investigación', 9),
('Subdirección Administrativa de Infraestructura Escolar', 9),
('Dirección Provincial de Infraestructura Escolar', 9),
('DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN, PROYECTO Y SEGUIMIENTO DE OBRAS', 9),
('DIRECCION PROVINCIAL DE EQUIPAMIENTO ESCOLAR', 9),
('Dirección Provincial de Mantenimiento', 9),
('Dirección Provincial de Educación Inicial', 9),
('Dirección Provincial de Educación Primaria', 9),
('Dirección Provincial de Educación Secundaria', 9),
('Dirección Provincial de Educación Superior', 9),
('Dirección Provincial de Educación Técnico-Profesional', 9),
('Dirección de Psicología Comunitaria y Pedagogía Social', 9),
('Dirección de Políticas Socioeducativas (Docente)', 9),
('Dirección de Educación Física', 9),
('Dirección de Educación Artística', 9),
('Dirección de Educación Jóvenes, Adultos y Adultos Mayores', 9),
('Dirección de Educación de Gestión Privada', 9),
('Dirección de Educación Especial', 9),
('Dirección de Coordinación y Seguimiento de la Gestión Territorial', 9),
('Dirección de Inspección General', 9),
('Dirección de Tribunal de Disciplina', 9),
('Dirección Tribunales de Clasificación', 9),
('Dirección de Concursos', 9),
('Dirección de Transporte y Logística', 9),
('Dirección Provincial de Gestión de Recursos Humanos', 9),
('Dirección Provincial de Asesoramiento Jubilatorio y Certificaciones', 9),
('Dirección Provincial de Contrataciones, Convenios y Administración de Inmuebles', 9),
('Dirección General de Administración', 9),
('Dirección Provincial de Tecnología de la Información', 9),
('Subdirección de Coordinación Institucional', 9),
('Subdirección de Coordinación de Actuaciones Judiciales', 9),
('Subdirección de Sumarios', 9),
('Dirección de Investigación', 9),
('DIRECCIÓN DE OBRAS Y MANTENIMIENTO ZONA SUR', 9),
('DIRECCIÓN DE OBRAS ZONAS NORTE Y CENTRO', 9),
('DIRECCIÓN DE MANTENIMIENTO ZONAS NORTE Y CENTRO', 9),
('Dirección de Formación Docente Inicial', 9),
('Dirección de Formación Docente Permanente', 9),
('Dirección de Educación Agraria', 9),
('Dirección de Educación Técnica', 9),
('Dirección de Educación Superior de Formación Técnica', 9),
('Dirección de Calidad Laboral y Medio Ambiente del Trabajo', 9),
('Dirección de Administración de Recursos Humanos', 9),
('Dirección de Gestión de Asuntos Docentes', 9),
('Dirección de Contralor Docente', 9),
('Dirección de Personal', 9),
('Dirección de Administración de Obras e Infraestructura Escolar', 9),
('Dirección de Compras y Contrataciones', 9),
('Dirección de Propiedades', 9),
('Dirección de Presupuesto', 9),
('Dirección de Contabilidad', 9),
('Dirección de Liquidaciones de Haberes, Retribuciones y Aportes a la Educación Privada', 9),
('Dirección de Finanzas', 9),
('Dirección de Desarrollo', 9),
('Dirección de Infraestructura y Producción', 9),
('Ministerio de Producción, Ciencia e Innovación Tecnológica', 5),
('Ente Administrador del Astillero Río Santiago', 5),
('GERENCIA GENERAL', 5),
('SUBGERENCIA GENERAL', 5),
('Fiscalía de Estado', 10),
('Fiscalía de Estado', 11),
('Fiscalías de Estado Adjuntas', 10),
('Fiscalías de Estado Adjuntas', 11),
('HONORABLE TRIBUNAL DE CUENTAS', 12),
('Vocalía Administración Central', 12),
('VOCALÍA REPARTICIONES AUTÁRQUICAS Y ENTES ESPECIALES', 12),
('VOCALÍA MUNICIPALIDADES A', 12),
('VOCALÍA MUNICIPALIDADES B', 12),
(' SECRETARÍA DE MODERNIZACIÓN Y FORTALECIMIENTO INSTITUCIONAL', 12),
('SECRETARÍA DE AUDITORÍAS FINANCIERAS Y PROYECTOS DE INVERSIÓN', 12),
('SECRETARÍA DE JURISPRUDENCIA, DOCTRINA Y CONSULTAS', 12),
('SECRETARÍA DE ACTUACIONES Y PROCEDIMIENTO', 12),
('SECRETARÍA DE LEGAL Y TÉCNICA', 12),
('PRESIDENCIA', 12),
('Relator Mayor VAC', 12),
('DELEGACIONES VAC', 12),
('RELATOR MAYOR VRAYEE', 12),
('DELEGACIONES VRAYEE', 12),
(' RELATOR MAYOR A', 12),
('RELATOR MAYOR B', 12),
('DIRECCIÓN GENERAL DE COORDINACIÓN CON DELEGACIONES, SISTEMAS Y ARCHIVO', 12),
('DIRECCIÓN GENERAL DE GESTIÓN DE LA CALIDAD', 12),
('DIRECCIÓN GENERAL DE AUDITORÍAS OPERACIONALES Y OMC', 12),
('RELATORÍA JEFE 1 DE AUDITORÍAS FINANCIERAS Y PROYECTOS DE INVERSIÓN', 12),
('RELATORÍA JEFE 2 DE AUDITORÍAS FINANCIERAS Y PROYECTOS DE INVERSIÓN', 12),
('DIRECCIÓN GENERAL DE ANÁLISIS TÉCNICO', 12),
('DIRECCIÓN GENERAL DE ASISTENCIA TÉCNICA', 12),
('DIRECCIÓN GENERAL DE LEGISLACIÓN Y JURISPRUDENCIA', 12),
('DIRECCIÓN GENERAL DE ACTUACIONES', 12),
('DIRECCIÓN GENERAL DE RECEPTORÍA Y PROCEDIMIENTO', 12),
(' SECRETARÍA EJECUTIVA DE ADMINISTRACIÓN Y RECURSOS HUMANOS', 12),
('SECRETARÍA DE RELACIONES INSTITUCIONALES Y PROFESIONALES', 12),
('Relatores VAC', 12),
('Relatores VAC', 13),
('Relatores VRAYEE', 12),
('RELATORES A', 12),
('RELATORES B', 12),
('RELATOR DE RELACIONES CON OMC', 12),
('Instituto Cultural de la Provincia de Buenos Aires', 14),
('VICEPRESIDENCIA DEL INSTITUTO CULTURAL DE LA PROVINCIA DE BUENOS AIRES', 14),
('SECRETARÍA EJECUTIVA', 14),
('Subsecretaría de Industrias Creativas e Innovación Cultural', 14),
('Dirección Provincial de Comunicación y Prensa Cultural', 14),
('Subsecretaría de Políticas Culturales', 14),
('Subsecretaría de Promoción Sociocultural', 14),
('SUBSECRETARÍA TÉCNICA, ADMINISTRATIVA Y LEGAL', 14),
('Dirección Provincial de Industrias Creativas y Economía de la Cultura', 14),
('Dirección Provincial de Promoción y Producción Cultural en Territorios', 14),
('Dirección General y Artística del Centro Provincial de las Artes Teatro Argentino', 14),
('Dirección Provincial de Patrimonio Cultural', 14),
('Dirección Provincial de Artes', 14),
('Dirección Provincial de Coordinación de Políticas Culturales', 14),
('DIRECCIÓN PROVINCIAL DE PROMOCIÓN DE LA LECTURA', 5),
('Dirección Provincial de Promoción Sociocultural', 14),
('Dirección General de Administración', 14),
('DIRECCIÓN PROVINCIAL TÉCNICA, ADMINISTRATIVA Y LEGAL', 14),
('Dirección de Estudios del Centro Provincial de las Artes Teatro Argentino', 14),
('Coordinación de los Organismos Artísticos del Sur', 14),
('Ministerio de Hábitat y Desarrollo Urbano', 13),
('INSTITUTO DE LA VIVIENDA', 13),
('Subadministración General', 13),
('GERENCIA TÉCNICA, ADMINISTRATIVA Y LEGAL', 13),
('GERENCIA TÉCNICA, ADMINISTRATIVA Y LEGAL', 3),
('GERENCIA DE OBRAS Y PROYECTOS URBANOS', 13),
('GERENCIA ESCRITURARIA Y SOCIAL', 13),
('GERENCIA DE DESARROLLO DE PROGRAMAS DE ACCESO AL CRÉDITO', 13),
('Ministerio de Salud', 15),
('Instituto de Obra Médico Asistencial (IOMA)', 15),
('IOMA (Vicepresidencia)', 15),
('DIRECTORIO (IOMA)', 15),
('Dirección Provincial de Prestaciones', 15),
('DIRECCIÓN GENERAL DE ADMINISTRACIÓN (IOMA)', 15),
('Dirección Provincial de Regiones, Atención y Cuidado del/de la Afiliado/a', 15),
('DIRECCIÓN PROVINCIAL DE TECNOLOGÍA, ANÁLISIS DE DATOS E INNOVACIÓN', 15),
('DIRECCIÓN PROVINCIAL DE RELACIONES INSTITUCIONALES Y JURÍDICAS', 15),
('DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN PRESTACIONAL Y GESTIÓN DIRECTA', 15),
('Ministerio de Trabajo', 16),
('INSTITUTO DE PREVISIÓN SOCIAL (IPS)', 16),
('Dirección General de Administración (IPS)', 16),
('PRESIDENCIA (IPS)', 16),
(' Dirección Provincial de Prestaciones', 16),
('Dirección Provincial de Territorialización', 16),
('DIRECCIÓN PROVINCIAL DE INFORMÁTICA Y TECNOLOGÍAS PREVISIONALES', 16),
('Directorio', 16),
('DIRECCIÓN REGIONAL (I a X)', 16),
('Dirección Gremial', 16),
('Dirección Gubernamental', 16),
('Instituto Provincial de Lotería y Casinos', 17),
('Instituto Provincial de Lotería y Casinos Vicepresidencia', 17),
('HIPÓDROMO DE LA PLATA', 17),
('Dirección Provincial de Juegos y Explotación', 17),
('Dirección Provincial de Administración y Finanzas', 17),
('Dirección Provincial de Hipódromos y Casinos', 17),
('HIPÓDROMO DE LA PLATA  SUBADMINISTRACIÓN GENERAL', 17),
('GERENCIA GENERAL DE ADMINISTRACIÓN Y FINANZAS', 17),
('GERENCIA GENERAL DE INFRAESTRUCTURA Y SERVICIOS', 17),
('GERENCIA GENERAL DE ACTIVIDAD HÍPICA', 17),
('Instituto Universitario Policial Provincial “Comisario General Honoris Causa Juan Vucetich”', 4),
('SECRETARÍA ACADÉMICA', 4),
('SECRETARÍA DE INVESTIGACIÓN', 4),
('SECRETARÍA DE EXTENSIÓN UNIVERSITARIA', 4),
('SECRETARÍA DE BIENESTAR ESTUDIANTIL', 4),
('SECRETARÍA ADMINISTRATIVA', 4),
('Gobernación de la Provincia de Buenos Aires', 18),
('JUNTA ELECTORAL', 18),
('SECRETARÍA DE ACTUACIÓN', 18),
('SECRETARÍA ADMINISTRATIVA', 18),
('SECRETARÍA DE MODERNIZACIÓN', 18),
('Vicepresidencia (JE)', 18),
('DIRECCIÓN GENERAL ELECTORAL', 18),
('DIRECCIÓN GENERAL DE ADMINISTRACIÓN (JE)', 18),
('Subsecretaría de Energía', 3),
('Organismo de Control de la Energía Eléctrica de la Provincia de Buenos Aires (O.C.E.B.A)', 3),
('O.C.E.B.A. (Vicepresidencia)', 3),
('Vocalía I (Directorio OCEBA)', 3),
('Vocalía II (Directorio OCEBA)', 3),
('Vocalía III (Directorio OCEBA)', 3),
('Organismo Provincial de Integración Social y Urbana', 13),
('Organismo Provincial de Integración Social y Urbana', 17),
('Dirección Provincial de Proyectos Urbanos', 17),
('Dirección Provincial de Proyectos Urbanos', 13),
('Dirección Provincial de Integración Social', 17),
('Dirección Provincial de Integración Social', 13),
('Dirección Provincial de Integración Productiva', 17),
('Dirección Provincial de Integración Productiva', 13),
('Dirección Provincial de Sistematización de Datos', 17),
('Dirección General de Administración (OPISU)', 13),
('DIRECCIÓN PROVINCIAL DE SISTEMAS DE INFORMACIÓN Y MONITOREO ESTRATÉGICO', 13),
('DIRECCIÓN PROVINCIAL DE EVALUACIÓN DE POLÍTICAS URBANAS Y CONTROL DE GESTIÓN', 13),
('DIRECCIÓN PROVINCIAL DE CONTROL Y SUPERVISIÓN DE PROYECTOS Y OBRAS', 13),
('DIRECCIÓN PROVINCIAL TÉCNICO LEGAL', 13),
('Ministerio de Desarrollo de la Comunidad', 19),
('Organismo Provincial de la Niñez y Adolescencia', 19),
('SUBSECRETARÍA DE PROMOCIÓN Y PROTECCIÓN DE DERECHOS', 19),
('SUBSECRETARÍA DE RESPONSABILIDAD PENAL JUVENIL', 19),
('DIRECCIÓN GENERAL DE ADMINISTRACIÓN (OPNYA)', 19),
('DIRECCIÓN PROVINCIAL DE EDUCACIÓN', 19),
('DIRECCIÓN PROVINCIAL DE ARTICULACIÓN INTERINSTITUCIONAL', 19),
('DIRECCIÓN PROVINCIAL DE PROMOCIÓN DE DERECHOS DE NIÑAS, NIÑOS Y ADOLESCENTES', 19),
('DIRECCIÓN PROVINCIAL DE PROTECCIÓN DE DERECHOS DE NIÑAS, NIÑOS Y ADOLESCENTES', 19),
('DIRECCIÓN PROVINCIAL DE COORDINACIÓN DE SERVICIOS ZONALES Y LOCALES', 19),
('DIRECCIÓN PROVINCIAL DE PROGRAMAS PENALES JUVENILES', 19),
('DIRECCIÓN PROVINCIAL DE ESTABLECIMIENTOS PENALES JUVENILES', 19),
('Ministerio de Justicia y Derechos Humanos', 20),
('Patronato de Liberados Bonaerense', 20),
('DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN, COORDINACIÓN Y CONTROL DE GESTIÓN', 20),
('DIRECCIÓN PROVINCIAL DE EJECUCIÓN PENAL EN LIBERTAD', 20),
('DIRECCIÓN PROVINCIAL DE REGIONES', 20),
('DIRECCIÓN GENERAL DE ADMINISTRACIÓN', 20),
('DIRECCIÓN DE COORDINACIÓN Y COMUNICACIÓN INSTITUCIONAL', 20),
('DIRECCIÓN DE EVALUACIÓN, INVESTIGACIÓN Y CAPACITACIÓN', 20),
('DIRECCIÓN DE PROGRAMAS Y TRATAMIENTO EN EL MEDIO LIBRE GRAN BUENOS AIRES', 20),
('DIRECCIÓN DE SISTEMAS INFORMÁTICOS', 20),
('DIRECCIÓN DE CONTROL DE LA EJECUCIÓN PENAL Y MEDIDAS JUDICIALES', 20),
('DIRECCIÓN REGIÓN (I A X)', 20),
('DIRECCIÓN DELEGADA DE LA DIRECCIÓN PROVINCIAL DE PERSONAL', 20),
('DIRECCIÓN DE SERVICIOS TÉCNICO ADMINISTRATIVO CONTABLE', 20),
('DIRECCIÓN DE SERVICIOS AUXILIARES', 20),
('SUBDIRECCIÓN DE ASISTENCIA Y TRATAMIENTO', 20),
('SUBDIRECCIÓN DE COORDINACIÓN DE SISTEMAS Y SOPORTE TÉCNICO', 20),
('SUBDIRECCIÓN DE CONTROL DE LA CONDENA Y MEDIDAS JUDICIALES', 20),
('Tesorería General de la Provincia', 21),
('Subtesorería General', 21),
('Secretaría General', 21),
('Dirección General de Planificación Financiera', 21),
('Dirección General de Supervisión Técnica', 21),
('Dirección General de Administración', 21),
('Dirección General de Planificación Estratégica y Rendiciones', 21),
('Dirección General de Pagos', 21),
('Dirección General Impositiva y Afectaciones Patrimoniales', 21),
('Dirección General de Sistemas', 21),
('DIRECCIÓN DE REGISTRACIÓN DE RECURSOS Y PARAMETRIZACIÓN DE GASTOS', 21),
('Dirección de Gastos en Personal y Sector Público', 21),
('DIRECCIÓN DE PAGOS', 21),
('Tribunal Fiscal de Apelación', 1),
('SALA I', 1),
('SALA II', 1),
('SALA III', 1);